FROM tensorflow/tensorflow:2.2.0-gpu
RUN apt-get update
RUN apt-get install -y zsh tmux wget git libsndfile1
RUN pip --default-timeout=600 install ipython && \
    pip --default-timeout=600 install git+https://github.com/TensorSpeech/TensorflowTTS.git && \
    pip --default-timeout=600 install grpcio-tools==1.31.0


RUN mkdir /workspace
WORKDIR /workspace

COPY ./ /workspace
